export const GET_SHARED_NOTES_DONE = "GET_SHARED_NOTES_DONE";
export const GET_SHARED_NOTES_LOADING = "GET_SHARED_NOTES_LOADING";
export const GET_SHARED_NOTES_FAILED = "GET_SHARED_NOTES_FAILED";
//
export const GET_SHARED_NOTE_DETAIL_DONE = "GET_SHARED_NOTE_DETAIL_DONE";
export const GET_SHARED_NOTE_DETAIL_LOADING = "GET_SHARED_NOTE_DETAIL_LOADING";
export const GET_SHARED_NOTE_DETAIL_FAILED = "GET_SHARED_NOTE_DETAIL_FAILED";
