export const ADD_NOTE_DONE = "ADD_NOTE_DONE";
export const ADD_NOTE_LOADING = "ADD_NOTE_LOADING";
export const ADD_NOTE_FAILED = "ADD_NOTE_FAILED";
//
export const GET_NOTES_DONE = "GET_NOTES_DONE";
export const GET_NOTES_LOADING = "GET_NOTES_LOADING";
export const GET_NOTES_FAILED = "GET_NOTES_FAILED";
//
export const GET_NOTE_DETAIL_DONE = "GET_NOTE_DETAIL_DONE";
export const GET_NOTE_DETAIL_LOADING = "GET_NOTE_DETAIL_LOADING";
export const GET_NOTE_DETAIL_FAILED = "GET_NOTE_DETAIL_FAILED";
//
export const PATCH_NOTE_DONE = "PATCH_NOTE_DONE";
export const PATCH_NOTE_LOADING = "PATCH_NOTE_LOADING";
export const PATCH_NOTE_FAILED = "PATCH_NOTE_FAILED";
