# Generated by Django 3.0.7 on 2020-12-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201201_2052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
        migrations.AlterModelTable(
            name='noteuser',
            table='note_user',
        ),
    ]
